### ISSUE TITLE
Network usage is prohibited for themes

### ISSUE THREAD

**Issue by joethei** [danyim/obsidian-zenburn#37]
It appears that your theme uses network connections to load assets (e.g. fonts, icons, or images). This is prohibited by the official [Obsidian developer policies](https://docs.obsidian.md/Developer+policies) because themes should function completely locally.

You can bundle an asset for local use by using data URLs. [See this guide](https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme). 

Please let us know if you have any questions. Any themes that use network connections will be removed from the official directory in the first week of January 2024.

- the Obsidian team

**Comment by danyim** [comment]
@joethei I embedded the fonts in the latest version: https://github.com/danyim/obsidian-zenburn/commit/3f01267de42d3efdedbca0c1ae92a3353ed571e9
